name: Checks

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  checks:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update && sudo apt-get install libegl1 libgl1-mesa-dev -y
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Windows dependencies
        if: startsWith(matrix.os, 'windows')
        run: |
          python -m pip install --upgrade pip
          pip install -r win_requirements.txt

      - name: Test with pytest
        run: |
          python runtests.py -vv --full-trace
